;
CREATE USER IF NOT EXISTS "SA" SALT '8e2a3a88c972f437' HASH 'b5a6d5f6d1ebe7fe4244a90a7c270586549503f73ba244527733a2511b58d308' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5A2CFB84_4425_4A1F_9AD7_EA64E99F2E47" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_619A0849_A01C_4440_BBCC_008ACAC781C6" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_144C0E2C_37D2_4EA2_AE20_00546FED7042" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_ACEAB33A_74A1_4F8D_B535_89EB074D1210" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_8E05611F_7EBE_4C43_A372_1B8BEFEF0282" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_42AEE8C4_7125_4DDA_A97E_CF61B964AF17" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."BILLBOARD"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_8E05611F_7EBE_4C43_A372_1B8BEFEF0282" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_8E05611F_7EBE_4C43_A372_1B8BEFEF0282",
    "STATUS" BOOLEAN NOT NULL,
    "DATE" DATE NOT NULL,
    "END_TIME" TIME NOT NULL,
    "START_TIME" TIME NOT NULL,
    "ID_MOVIE" INTEGER NOT NULL,
    "ID_ROOM" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."BILLBOARD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BILLBOARD;
CREATE CACHED TABLE "PUBLIC"."BOOKING"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_ACEAB33A_74A1_4F8D_B535_89EB074D1210" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_ACEAB33A_74A1_4F8D_B535_89EB074D1210",
    "STATUS" BOOLEAN NOT NULL,
    "DATE" TIMESTAMP NOT NULL,
    "ID_BILLBOARD" INTEGER NOT NULL,
    "ID_CUSTUMER" INTEGER NOT NULL,
    "ID_SEAT" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."BOOKING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BOOKING;
CREATE CACHED TABLE "PUBLIC"."CUSTOMER"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_619A0849_A01C_4440_BBCC_008ACAC781C6" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_619A0849_A01C_4440_BBCC_008ACAC781C6",
    "STATUS" BOOLEAN NOT NULL,
    "AGE" SMALLINT NOT NULL CHECK ("AGE" >= 1),
    "DOCUMENT_NUMBER" VARCHAR(20) NOT NULL,
    "EMAIL" VARCHAR(100),
    "LASTNAME" VARCHAR(30) NOT NULL,
    "NAME" VARCHAR(30) NOT NULL,
    "PHONE_NUMBER" VARCHAR(20)
);
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER;
CREATE CACHED TABLE "PUBLIC"."MOVIE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_42AEE8C4_7125_4DDA_A97E_CF61B964AF17" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_42AEE8C4_7125_4DDA_A97E_CF61B964AF17",
    "STATUS" BOOLEAN NOT NULL,
    "ALLOWED_AGE" SMALLINT NOT NULL CHECK ("ALLOWED_AGE" >= 1),
    "GENRE" VARCHAR(30) NOT NULL,
    "LENGTH_MINUTES" SMALLINT NOT NULL CHECK ("LENGTH_MINUTES" >= 1),
    "NAME" VARCHAR(30) NOT NULL
);
ALTER TABLE "PUBLIC"."MOVIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MOVIE;
CREATE CACHED TABLE "PUBLIC"."ROOM"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_144C0E2C_37D2_4EA2_AE20_00546FED7042" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_144C0E2C_37D2_4EA2_AE20_00546FED7042",
    "STATUS" BOOLEAN NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "NUMBER" SMALLINT NOT NULL CHECK ("NUMBER" >= 1)
);
ALTER TABLE "PUBLIC"."ROOM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_26" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROOM;
CREATE CACHED TABLE "PUBLIC"."SEAT"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5A2CFB84_4425_4A1F_9AD7_EA64E99F2E47" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5A2CFB84_4425_4A1F_9AD7_EA64E99F2E47",
    "STATUS" BOOLEAN NOT NULL,
    "NUMBER" SMALLINT NOT NULL CHECK ("NUMBER" >= 1),
    "ROW_NUMBER" SMALLINT NOT NULL CHECK ("ROW_NUMBER" >= 1),
    "ID_ROOM" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."SEAT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_26C" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SEAT;
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."UK_MCXHS25405P3P7MRRE6HE23NF" UNIQUE("DOCUMENT_NUMBER");
ALTER TABLE "PUBLIC"."BILLBOARD" ADD CONSTRAINT "PUBLIC"."FK_MOVIE_BILLBOARD" FOREIGN KEY("ID_MOVIE") REFERENCES "PUBLIC"."MOVIE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."SEAT" ADD CONSTRAINT "PUBLIC"."FK_ROOM_SEAT" FOREIGN KEY("ID_ROOM") REFERENCES "PUBLIC"."ROOM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BOOKING" ADD CONSTRAINT "PUBLIC"."FK_CUSTOMER_BOOKING" FOREIGN KEY("ID_CUSTUMER") REFERENCES "PUBLIC"."CUSTOMER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BILLBOARD" ADD CONSTRAINT "PUBLIC"."FK_ROOM_BILLBOARD" FOREIGN KEY("ID_ROOM") REFERENCES "PUBLIC"."ROOM"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BOOKING" ADD CONSTRAINT "PUBLIC"."FK_SEAT_BOOKING" FOREIGN KEY("ID_SEAT") REFERENCES "PUBLIC"."SEAT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."BOOKING" ADD CONSTRAINT "PUBLIC"."FK_BILLBOARD_BOOKING" FOREIGN KEY("ID_BILLBOARD") REFERENCES "PUBLIC"."BILLBOARD"("ID") NOCHECK;


insert into movie values (null, true, 18, 'HORROR', 120, 'CHUCKY');
insert into movie values (null, true, 12, 'COMEDY', 120, 'MI POBRE ANGELITO');
insert into movie values (null, true, 18, 'ACTION', 120, 'RAMBO');

insert into room values(null, true, 'SALA 1', 1);
insert into room values(null, true, 'SALA 2', 2);
insert into room values(null, true, 'SALA 3', 3);